### ISSUE TITLE
Images not working!

### ISSUE THREAD

**Issue by Etzshally** [cahilfoley/react-snowfall#77]
Kindly resolve issue when using with react, images doesnt work. it gives an error of weak map..

**Comment by cahilfoley** [comment]
Hey there, is there any chance you could provide a reproduction of this?

You can have a look at the [Demo Playground](https://codesandbox.io/s/github/cahilfoley/react-snowfall/tree/main/packages/demo) that works and has an option to swap out the snowflakes for images.

**Comment by yceballost** [comment]
Same here. I follow the instructions but the images don't work

![image](https://github.com/user-attachments/assets/a0ad9401-085e-4469-be39-25fa3a12144d)

without images, works perfect.

**Comment by yceballost** [comment]
don't know why, but this is working

```
import snowflakeSrc1 from "../assets/snowflake-1.svg";
import snowflakeSrc2 from "../assets/snowflake-2.svg";

const snowflake1 = document.createElement("img");
  snowflake1.src = snowflakeSrc1;
  const snowflake2 = document.createElement("img");
  snowflake2.src = snowflakeSrc2;

  const customSnow = [snowflake1, snowflake2];

return (
      <Snowfall
        color="#EEF0FB"
        radius={[50, 50]}
        speed={[1.0, 2.0]} // default [1.0, 3.0]
        snowflakeCount={20}
        images={customSnow}
        // snowflakeCount={Math.floor(Math.random() * (2000 - 200 + 1)) + 200}
      />
)
```

**Comment by cahilfoley** [comment]
This issue stems from the fact that the images need to have loaded before they are provided to the canvas to render - if it started suddenly working after a second attempt it's likely due to the image being loaded from the HTTP cache or some other mechanism fast enough to be available for the first snowfall render.

There's an explanation and some example code in [this comment on another closed issue](https://github.com/cahilfoley/react-snowfall/issues/59#issuecomment-2428063131) that gives a working example that works reliably for the same issue.
